---
version: 1

kind: group

framework: pytorch

tags: [unet, wandb, thyroid, exp_set, us_thyroid_cross_valid_1]

build:
  image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
  build_steps:
    - echo "please work"
    - apt update
    - apt install gcc python3 python3-pip -y
    - python3 -m pip install -U --no-cache-dir polyaxon_client
    - pip install -r requirements.txt
  env_vars:
    - ["TORCH_HOME", "/data1/PytorchModelZoo"]
    - ["CUDA_LAUNCH_BLOCKING", 1]

environment:
  resources:
    cpu:
      requests: 3
      limits: 3
    memory:
      requests: 10240 #16384 #10240 #8192 #4096 #2048
      limits: 24576 #32768 #24576 #16384 #8192 #4096
    gpu:
      requests: 1
      limits: 1

hptuning:
  concurrency: 4
  matrix:
    loss:
      values: ["dice_ce", "cross_entropy"] # "dice"
    cm_channel:
      values: ["add-cm-ch", "no-add-cm-ch"]
    cm_loss:
      values: ["add-cm-loss", "no-add-cm-loss"]

params:
  batch_size_train: 2 #8
  batch_size_test: 2 #16
  lr: 0.001
  resize: 128 #96 #144
  cache_num: 1
  epochs: 120
  network: unet
  data_dir: /vanessagd/Monai_Projects/Ifssnet/thyroid_even_xv2/imagesTr
  wandb: "wandb" # wandb / no-wandb
  wandb_key: "ebc2a5f87292a5eb270a5a7cd8fc74355c7cd924"
  wandb_project: "us_thyroid_cross_valid_2"

run:
  cmd:
    python3 -u -m deepatlas.main \
    --polyaxon  \
    --{{ wandb }} \
    --wandb-key {{ wandb_key }} \
    --wandb-project {{ wandb_project }} \
    train \
    --batch-size={{ batch_size_train }} \
    --test-batch-size={{ batch_size_test }} \
    --epochs={{ epochs }} \
    --lr={{ lr }} \
    --resize={{ resize }} \
    --cache-num={{ cache_num }} \
    --data-dir={{ data_dir }} \
    --network={{ network }} \
    --solo-seg \
    --{{ cm_channel }} \
    --{{ cm_loss }} \
    --loss={{ loss }}
