---
version: 1

kind: experiment

framework: pytorch

tags: [no_deepatlas, us_data, group, unet, unetr]

build:
  image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
  build_steps:
    - apt update
    - apt install gcc python3 python3-pip -y
    - python3 -m pip install -U --no-cache-dir polyaxon_client
    - pip install -r requirements.txt
  env_vars:
    - ["TORCH_HOME", "/data1/PytorchModelZoo"]
    - ["CUDA_LAUNCH_BLOCKING", 1]

environment:
  resources:
    cpu:
      requests: 3
      limits: 3
    memory:
      requests: 10240 #10240 #8192 #4096 #2048
      limits: 24576 #24576 #16384 #8192 #4096
    gpu:
      requests: 1
      limits: 1

params:
  batch_size_train: 2 #8
  batch_size_test: 2 #16
  lr: 0.001
  resize: 128 #96 #144
  cache_num: 1
  data_dir: vanessagd/Monai_Projects/Ifssnet/Left/imagesTr
  test_data_dir: vanessagd/Monai_Projects/Ifssnet/Left/imagesTs
  network: "unetr"
  epochs: 10
  conf_maps: "conf-maps" # conf-maps / no-conf-maps
  wandb: "wandb" # wandb / no-wandb
  wandb_key: "ebc2a5f87292a5eb270a5a7cd8fc74355c7cd924"
  wandb_project: "ultrasound_confidence_maps"

run:
  cmd:
    python3 -u -m deepatlas.main \
            --polyaxon  \
            --{{ wandb }} \
            --wandb-key {{ wandb_key }} \
            --wandb-project {{ wandb_project }} \
          train \
            --batch-size={{ batch_size_train }} \
            --test-batch-size={{ batch_size_test }} \
            --epochs={{ epochs }} \
            --lr={{ lr }} \
            --resize={{ resize }} \
            --cache-num={{ cache_num }} \
            --data-dir={{ data_dir }} \
            --network={{ network }} \
            --solo-seg \
            --{{ conf_maps }} \
          infer \
            --data-dir={{ test_data_dir }}
