---
version: 1

kind: experiment

framework: pytorch

tags: [deepatlas, oasis, full_run]

build:
  image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
  build_steps:
    - ls -Ral # log for debug
    - apt update
    - apt install gcc -y
    - python3 -m pip install -U --no-cache-dir polyaxon_client
    - pip install -r requirements.txt
  env_vars:
    - ["TORCH_HOME", "/data1/PytorchModelZoo"]
    - ["CUDA_LAUNCH_BLOCKING", 1]

environment:
  resources:
    cpu:
      requests: 3
      limits: 3
    memory:
      requests: 4096 #4096 #2048
      limits: 8192 #8192
    gpu:
      requests: 1
      limits: 1

params:
  batch_size_train: 8 #8
  batch_size_test: 16 #16
  epochs: 60 # 60
  lr: 0.001
  resize: 128 #96 #144
  cache_num: 2 #should to be divisible by 2
  limit: 4 # limits segmentation to simulate less train-data
  # === Train Context ===
  lambda_a: 2.0
  lambda_sp: 3.0
  lambda_r_multiplier: 7.5
  reg_phase_training_batches_per_epoch: 40
  seg_phase_training_batches_per_epoch: 5
  reg_phase_num_validation_batches_to_use: 40
  val_interval: 5

run:
  cmd:
    python3 -u -m deepatlas.main --polyaxon train \
    --batch-size={{ batch_size_train }} \
    --test-batch-size={{ batch_size_test }} \
    --epochs={{ epochs }} \
    --lr={{ lr }} \
    --resize={{ resize }} \
    --cache-num={{ cache_num }} \
    --limit={{ limit }} \
    --train-context='{"lambda_a":{{ lambda_a }},"lambda_sp":{{ lambda_sp }},"lambda_r_multiplier":{{ lambda_r_multiplier }},"reg_phase_training_batches_per_epoch":{{ reg_phase_training_batches_per_epoch }},"seg_phase_training_batches_per_epoch":{{ seg_phase_training_batches_per_epoch }},"reg_phase_num_validation_batches_to_use":{{ reg_phase_num_validation_batches_to_use }},"val_interval":{{ val_interval }}}' \
    --pretrain-seg \
    --oasis \
    infer --metrics
