---
version: 1

kind: experiment

framework: pytorch

tags: [new_data, group, deepatlas, wandb]

build:
  image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
  # nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04
  # pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime # TODO wrong python version
  # image: pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime
  build_steps:
    - apt update
    - apt install gcc python3 python3-pip -y
    - python3 -m pip install -U --no-cache-dir polyaxon_client
    - pip install -r requirements.txt
  env_vars:
    - ["TORCH_HOME", "/data1/PytorchModelZoo"]
    - ["CUDA_LAUNCH_BLOCKING", 1]

environment:
  resources:
    cpu:
      requests: 3
      limits: 3
    memory:
      requests: 10240 #8192 #4096 #2048
      limits: 24576 # 16384 #8192
    gpu:
      requests: 1
      limits: 1

params:
  batch_size_train: 2 #8
  batch_size_test: 2 #16
  epochs: 60 # 60
  lr: 0.001
  resize: 128 #96 #144
  cache_num: 1
  # data_dir: vanessagd/Monai_Projects/DeepAtlas/deepatlas_small_preprocessed/imagesTr/
  # test_data_dir: vanessagd/Monai_Projects/DeepAtlas/deepatlas_small_preprocessed/imagesTs/
  data_dir: vanessagd/Monai_Projects/Ifssnet/Left/imagesTr
  test_data_dir: vanessagd/Monai_Projects/Ifssnet/Left/imagesTs
  pretrain: "pretrain-seg"
  # === Train Context ===
  lambda_a: 2.0
  lambda_sp: 3.0
  lambda_r_multiplier: 7.5
  reg_phase_training_batches_per_epoch: 40
  seg_phase_training_batches_per_epoch: 5
  reg_phase_num_validation_batches_to_use: 40
  val_interval: 5

run:
  cmd:
    python3 -u -m deepatlas.main \
    --polyaxon  \
    --wandb \
    --wandb-key ebc2a5f87292a5eb270a5a7cd8fc74355c7cd924 \
    train \
    --batch-size={{ batch_size_train }} \
    --test-batch-size={{ batch_size_test }} \
    --epochs={{ epochs }} \
    --lr={{ lr }} \
    --resize={{ resize }} \
    --cache-num={{ cache_num }} \
    --data-dir={{ data_dir }} \
    --{{ pretrain }} \
    --train-context='{"lambda_a":{{ lambda_a }},"lambda_sp":{{ lambda_sp }},"lambda_r_multiplier":{{ lambda_r_multiplier }},"reg_phase_training_batches_per_epoch":{{ reg_phase_training_batches_per_epoch }},"seg_phase_training_batches_per_epoch":{{ seg_phase_training_batches_per_epoch }},"reg_phase_num_validation_batches_to_use":{{ reg_phase_num_validation_batches_to_use }},"val_interval":{{ val_interval }}}' \
    # infer \
    # --data-dir {{ test_data_dir }} \
    # --save-ram
